name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_CONTACT_SERVER_LINK: ${{ secrets.REACT_APP_CONTACT_SERVER_LINK }}
          REACT_APP_VIEWS_SERVER_LINK: ${{ secrets.REACT_APP_VIEWS_SERVER_LINK }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: build
