name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean -f

      - name: Install dependencies
        run: npm install

      - name: Debug info
        run: |
          ls -l   # Afișează conținutul directorului pentru depanare
          npm ls  # Afișează structura dependențelor pentru depanare

      - name: Build
        run: |
          npm run-script build
        env:
          REACT_APP_CONTACT_SERVER_LINK: ${{ secrets.REACT_APP_CONTACT_SERVER_LINK }}
          REACT_APP_VIEWS_SERVER_LINK: ${{ secrets.REACT_APP_VIEWS_SERVER_LINK }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: build
